# General application settings
spring.application.name=${SPRING_APPLICATION_NAME:Complaint Management System}
server.forward-headers-strategy=FRAMEWORK
server.port=${PORT:8080}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# Allow up to 5000 results per page
spring.data.web.pageable.max-page-size=5000

# Logging levels
logging.level.com.system.complaints.service=${LOGGING_LEVEL_COMPLAINTS_SERVICE:INFO}
logging.level.org.springframework.security=${LOGGING_LEVEL_SPRING_SECURITY:INFO}

# File upload path
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
complaintimages.upload.path=${COMPLAINTIMAGES_UPLOAD_PATH:/tmp/complaint_images}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Dotenv support
dotenv.enabled=true
dotenv.overload=true

# Session
server.servlet.session.timeout=604800
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
